# These are supported funding model platforms
github: # DivySrivastava, dan-online
patreon: dan_divy
open_collective: dan_divy
ko_fi: dan_divy
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: dan_divy
issuehunt: divysrivastava
otechie: # Replace with a single Otechie username
custom: # Replace with a single custom sponsorship URL
